#FROM yamsergey/bb10-ndk:0.6 as yam

FROM i386/ubuntu:20.04
COPY --from=yamsergey/bb10-ndk:0.6 /root/bbndk /root/bbndk
RUN chown -R 65534:65534 /root

#RUN export DEBIAN_FRONTEND=noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN apt-get -q update ;\
    export TZ=Europe/Paris; \
    apt-get -yq install \
    tzdata \
    wget \
    sudo \
    unzip \
    curl \
    tar \
    gzip \
    bzip2 \
    ruby \
    git \
    curl \
    texinfo \
    autopoint \
    m4 \
    autoconf \
    groff \
    libgtk2.0-0 \
    gcc \
    libxtst6 \
    net-tools \
    g++ \
    zlib1g-dev \
    file \
    make

#RUN wget https://dl.google.com/go/go1.17.7.linux-amd64.tar.gz 
RUN wget https://dl.google.com/go/go1.17.7.linux-386.tar.gz

RUN sudo mkdir /opt ;\
    sudo tar -xvf go1.17.7.linux-386.tar.gz -C /opt ;\
    rm go1.17.7.linux-386.tar.gz

RUN wget https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip ; \
    sudo unzip -d /opt android-ndk-r18b-linux-x86_64.zip ; \
    rm android-ndk-r18b-linux-x86_64.zip


#ENV PATH=/opt/go/bin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/android-ndk-r18b/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin 


# FROM https://github.com/golang/go/wiki/Mobile
#RUN export PATH=$PATH:/opt/android-ndk-r18b/prebuilt/linux-x86_64:/opt/android-ndk-r18b/simpleperf/bin:/opt/android-ndk-r18b/simpleperf/bin:/opt/android-ndk-r18b/simpleperf/bin/androidx86:/opt/android-ndk-r18b/simpleperf/bin/androidx86_64:/opt/android-ndk-r18b/simpleperf/bin/linuxx86:/opt/android-ndk-r18b/simpleperf/bin/linuxx86_64:/opt/android-ndk-r18b/toolchains/aarch64-linux-android-4.9/prebuiltlinux-x86_64:/opt/android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuiltlinux-x86_64:/opt/android-ndk-r18b/toolchains/llvm/prebuiltlinux-x86_64:/opt/android-ndk-r18b/toolchains/renderscript/prebuiltlinux-x86_64:/opt/android-ndk-r18b/toolchains/x86-4.9/prebuiltlinux-x86_64:/opt/android-ndk-r18b/toolchains/x86_64-4.9/prebuiltlinux-x86_64

#RUN echo TEST DEBUG x86_64-linux-android-gcc

# we must add this as option $CC --sysroot=
#bin/x86_64-linux-android-gcc
#                 /opt/android-ndk-r18b/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin/x86_64-linux-android-gcc

#$ echo $PATH
#/opt/android-ndk-r9/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin:
#/opt/android-sdk-macosx/tools/:/opt/android-sdk-macosx/platform-tools/:/opt/local/bin:

#$ echo $LD
#arm-linux-androideabi-ld

RUN export CPP=cpp
RUN export CC=gcc
RUN export CXX=g++
RUN export LD=ld
RUN export AS=as
RUN export AR=ar
RUN export RANLIB=ranlib

#export ANDROID_SYSROOT=/opt/android-ndk-r18b/toolchains/x86_64-4.9/prebuilt/linux-x86_64
#	/bin/x86_64-linux-android-gcc

#export ANDROID_SYSROOT=/opt/android-ndk-r18b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64
#     	/bin/aarch64-linux-android-gcc

#export ANDROID_SYSROOT=/opt/android-ndk-r18b/toolchains/x86-4.9/prebuilt/linux-x86_64
#	/bin/i686-linux-android-gcc

#export ANDROID_SYSROOT=/opt/android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
#	/bin/arm-linux-androideabi-gcc

#/crtbegin_dynamic.o
#RUN export LD_LIBRARY_PATH=/opt/android-ndk-r18b/platforms/android-18/arch-x86/usr/lib
#RUN export LD_LIBRARY_PATH=/opt/android-ndk-r18b/toolchains/x86_64-4.9/prebuilt/linux-x86_64

# may be used also via cli option --sysroot=/opt/android-ndk-r9/platforms/android-18/arch-arm

RUN ANDROID_SYSROOT=/opt/android-ndk-r18b/toolchains/x86_64-4.9/prebuilt/linux-x86_64
RUN export CPPFLAGS="--sysroot=$ANDROID_SYSROOT"
RUN export CFLAGS="--sysroot=$ANDROID_SYSROOT"
RUN export CXXFLAGS="--sysroot=$ANDROID_SYSROOT"

#RUN strace -v -s 8192 -f go install golang.org/x/mobile/cmd/gomobile@latest 2>&1 | tee -a /tmp/detect
RUN go install golang.org/x/mobile/cmd/gomobile@latest 2>&1 | tee -a /tmp/detect
