name: CI

on:
  push:
    branches: [ main, master, wip ]

jobs:
  build:
    runs-on: [ Linux-x86_64:host, berrymuch:host, Linux-amd64, Linux-x86_64 ]
    steps:
      - name: Clone 
        uses: actions/checkout@v4
        with:
          depth: 1
          branch: 'main'
          repository: 'kalou/berrymuch'
      - name: "Find last updated WIP port and build"
        run: |
          PFX=$HOME/berrymuch
          # Find the last updated directory in $PFX/ports-wip/
          PORT_NAME=$(ls -1t "$PFX/ports-wip/" | head -n1)
          echo "Last updated port: $PORT_NAME"
          make build-wip.$PORT_NAME
