name: CI

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      matrix:
        runner: [Linux-x86_64]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Print hostname
        run: make build.nano
