name: CI

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: [berrymuch]
    steps:
      - name: "Find last updated WIP port and build"
        run: |
          PFX=$(HOME)/berrymuch
          # Find the last updated directory in $PFX/ports-wip/
          PORT_NAME=$(ls -1t "$PFX/ports-wip/" | head -n1)
          echo "Last updated port: $PORT_NAME"
          cd "$PFX/ports-wip/$PORT_NAME"
          bash -x ./build.sh
