version: 2.1
jobs:
  test:
    docker: 
      - image: yamsergey/bb10-ndk:0.3
    steps:
      - checkout
      - run: ./build.sh -b /root/bbndk -t build 
    filters:
      branches:
        only: master        
workflows:
  version: 2.1
  test:
    jobs:
      - test
